#!/bin/bash
# Install-pre script for FC3 OS template

set -e
set -u
cd $VE_ROOT
mkdir -p var/lib/rpm
mkdir -p var/lock/rpm
$RPM --root $VE_ROOT --initdb

mkdir -p dev
mknod dev/null c 1 3
chmod 0666 dev/null
